#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

set -o xtrace

. /lib/svc/share/smf_include.sh

PATH=/usr/sbin:/usr/bin; export PATH

case "$1" in
'start')
    ENABLED=$(json -f /opt/smartdc/napi-ufds-watcher/etc/config.json overlay.enabled)
    if [[ $ENABLED == "false" ]]; then
        echo "Fabrics not configured, not starting watcher daemon.";
        exit $SMF_EXIT_NODAEMON;
    else
        /usr/bin/ctrun -l child -o noorphan /opt/smartdc/napi-ufds-watcher/build/node/bin/node /opt/smartdc/napi-ufds-watcher/main.js -f /opt/smartdc/napi-ufds-watcher/etc/config.json &
    fi
    ;;

'stop')
    ;;

*)
    echo "Usage: $0 { start | stop }"
    exit $SMF_EXIT_ERR_FATAL
    ;;
esac
exit $SMF_EXIT_OK
