#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# Rsync the master in this working copy to the install on the given HN.
#

# set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE=$1

if [[ -z "$SDC_ZONE" ]]; then
    SDC_ZONE=$(ssh $NODE "/opt/smartdc/bin/sdc-vmapi /vms" 2>/dev/null \
        | json -H -c 'this.tags && this.tags.smartdc_role === "sdc"' \
            -c 'this.state === "running"' 0.uuid)
fi
echo "SDC_ZONE: $SDC_ZONE"

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
else
    # Clean node_modules everytime.
    ssh $NODE rm -rf /zones/$SDC_ZONE/root/opt/smartdc/napi-ufds-watcher/node_modules
fi

rsync -av ${TOP}/ \
    $NODE:/zones/$SDC_ZONE/root/opt/smartdc/napi-ufds-watcher \
    $extraOpts \
    --exclude .git/ \
    --exclude /etc/config.json \
    --exclude /deps/ \
    --exclude /docs/ \
    --exclude /tools/ \
    --exclude /tmp/

state=$(ssh ${NODE} "svcs -z ${SDC_ZONE} -H -o state napi-ufds-watcher" || true)

if [[ -z $state ]]; then
    # state is empty, probably don't have smf yet.
    ssh ${NODE} zlogin ${SDC_ZONE} "svccfg import /opt/smartdc/napi-ufds-watcher/smf/manifests/napi-ufds-watcher.xml"
elif [[ "$state" == "maintenance" ]]; then
    ssh ${NODE} svcadm -z ${SDC_ZONE} clear napi-ufds-watcher
else
    ssh ${NODE} svcadm -z ${SDC_ZONE} restart napi-ufds-watcher
fi

# copy templates
ssh ${NODE} cp -r /zones/${SDC_ZONE}/root/opt/smartdc/napi-ufds-watcher/sapi_manifests/napi-ufds-watcher \
    /zones/${SDC_ZONE}/root/opt/smartdc/sapi_manifests

ssh ${NODE} svcadm -z ${SDC_ZONE} restart config-agent
